[package]
name = "dialoguemaker/dialogue-content-fitter-types"
version = "0.1.0-patch-3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
repository = "https://github.com/DialogueMaker/effect-types"
authors = ["Christian Toney <christian.toney@beastslash.com>"]
include = ["src", "src/**/*.lua", "wally.toml", "default.project.json"]
exclude = ["**"]

[dependencies]
effect-types = "dialoguemaker/effect-types@0.1.0-patch-3"