[package]
name = "dialoguemaker/dialogue-content-fitter-types"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
effect-types = "dialoguemaker/effect-types@0.1.0"